Latin = [
    'Primus terminus range specificare: ',
    'Secundus terminus range specificare: ',
    'Ascende numerus in latitudine ',
    'e* ',
    'usque ',
    'Ex parte.',
    'Estne ',
    'numerus major est ',
    'numerus est minus, quam ',
    'numerus est ',
    'Conjectura!',
    'Mendax.',
    'Vos postulo ut typus ']
English = [
    'Specify the first range limit: ',
    'Specify the second range limit: ',
    'Come up with a total number in the range ',
    'from ',
    'to ',
    'Out of range.',
    'Is it ',
    'number is greater than ',
    'number is lower than ',
    'the number is ',
    'I guessed it!',
    'Liar.',
    'You need to type in ']
Polish = [
    'Podaj pierwszy limit zakresu: ',
    'Podaj drugi limit zakresu: ',
    'Wymyśl całkowitą liczbę w zakresie ',
    'od ',
    'do ',
    'Poza zakresem.',
    'Czy to ',
    'liczba jest większa od ',
    'liczba jest mniejsza od ',
    'liczbą jest ',
    'Zgadłem!',
    'Kłamco.',
    'Trzeba wpisać ']
Ukrainian = [
    'Укажіть першу межу діапазону: ',
    'Вкажіть другу межу діапазону: ',
    'Придумайте загальне число у діапазоні ',
    'від ',
    'до ',
    'За межою.',
    'Є це ',
    'число більше ніж ',
    'число менше ніж ',
    'число є ',
    'Вгадав!',
    'Брехун.',
    'Тобі потрібно ввести ']
Russian = [
    'Укажите первый предел диапазона: ',
    'Укажите второй предел диапазона: ',
    'Придумайте общее число в диапазоне ',
    'од ',
    'до ',
    'Вне диапазона.',
    'Это ',
    'число больше ',
    'число меньше ',
    'загаданное число ',
    'Угадал!',
    'Лжец.',
    'Тебе нужно ввести ']
Sindarin = [
    'Specifui i erui lír limit: ',
    'Specifui i second lír limit: ',
    'Tul- or- with a total gwanod in i lír ',
    'o ',
    'na ',
    'Ed- -o lír.',
    'Na- ha ',
    'gwanod na- greater than ',
    'gwanod na- lower than ',
    'i gwanod na- ',
    'Im guessed ha!',
    'Liar.',
    'Cin baur na type in ']
Orcish = [
    'Specify ul first range limit: ',
    'Specify ul second range limit: ',
    'Dez tog ar ij total number shal ul range ',
    'kor ',
    've ',
    'Out ro range.',
    'Ku khe ',
    'number ku greater than ',
    'number ku lower than ',
    'ul number ku ',
    'Jiak guessed khe!',
    'Liar.',
    'Lat need ve type shal ']
Valyrian = [
    'Specify se ēlī range limit: ',
    'Specify se tȳne range limit: ',
    'Māzigon bē rūsīr nykeā total number isse se range ',
    'hen ',
    'naejot ',
    'Hen hen range.',
    'Iksos ziry ',
    'number iksos greater than ',
    'number iksos lower than ',
    'se number iksos ',
    'Nyke guessed ziry!',
    'Liar.',
    'Ao jorrāelagon naejot type isse ']
